CREATE DATABASE BDimagem
GO
USE BDimagem
GO

CREATE TABLE TBLimagem
(
	Id INT IDENTITY PRIMARY KEY,
	Placa VARCHAR (8),
	Renavan VARCHAR (11),
	Nome VARCHAR (50),
	CPF VARCHAR (11),
	imagem VARCHAR (5000)
)